server:
  port: 8083

spring:
  application:
    name: eureka-rabbitmq
  #rabbitmq信息
  rabbitmq:
    host: 39.108.134.71
    port: 5672
    username: 15102356906
    password: 016312Aj.713
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8081/eureka/